[package]
name = "miner"
version = "0.1.0"
authors = ["James Hilton-Balfe <jhiltonbalfe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "_miner"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4"
lazy_static = "1.4"

[dependencies.pyo3]
version = "0.15.0"
features = ["extension-module"]

